Repository uhafner/quality-monitor, pull requests merged in 2025-03, with the labels that each got.

#80 Bump version of autograding-model to 6.0.0
  pom.xml
Labels: enhancement

#84 Bump version of autograding to 6.2.0
  pom.xml
Labels: dependencies

#86 Add support for GHE by adding a parameter for the API URL
  README.md
  action.yml
  src/main/java/edu/hm/hafner/grading/github/QualityMonitor.java
Labels: enhancement

#87 Remove duplicate env section
  action.yml
  doc/dependency-graph.puml
  pom.xml
  src/test/java/edu/hm/hafner/grading/github/QualityMonitorDockerITest.java
Labels: bug

#88 Write GitHub comments even if the checks results fails
  .github/workflows/quality-monitor.yml
  action.yml
  doc/dependency-graph.puml
  pom.xml
  src/main/java/edu/hm/hafner/grading/github/QualityMonitor.java
  src/test/java/edu/hm/hafner/grading/github/QualityMonitorDockerITest.java
Labels: bug

#89 Use the default message if the HTTP response message is `null`
  action.yml
  doc/dependency-graph.puml
  pom.xml
  src/main/java/edu/hm/hafner/grading/github/QualityMonitor.java
  src/test/java/edu/hm/hafner/grading/github/QualityMonitorDockerITest.java
Labels: bug
